Update CI.yml
This commit consolidates 12 consecutive commits by Ruixin Song.

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -118,13 +118,53 @@ jobs:
           cargo install --locked wasm-bindgen-cli --verbose
           cargo install --locked wasm-opt --verbose
           wasm-pack --version
-      - name: Setup PostgreSQL
+
+      - name: Stop PostgreSQL 16 Service
+        run: |
+          if systemctl is-active --quiet postgresql@16-main; then
+            echo "PostgreSQL 16 is active. Stopping and removing it."
+            sudo systemctl stop postgresql@16-main
+            sudo apt-get remove --purge -y postgresql-16 postgresql-client-16 || true
+            sudo apt-get autoremove -y
+            sudo apt-get autoclean -y
+          else
+            echo "PostgreSQL 16 is not active. No need to stop or remove it."
+          fi
+          
+      - name: Setup PostgreSQL 17 Default
         run: |
           sudo apt-get update -y
-          sudo apt-get install postgresql -y
-          sudo systemctl enable postgresql
-          sudo systemctl start postgresql
+          sudo apt-get upgrade -y
+          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y gnupg postgresql-common apt-transport-https lsb-release wget
+          sudo apt-get install -y postgresql-17 postgresql-client-17 postgresql-server-dev-17
+          # echo | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
+          # sudo apt-get install -y postgresql-server-dev-17
+          sudo systemctl enable postgresql@17-main
+          sudo systemctl start postgresql@17-main
+          echo "Checking PostgreSQL port from configuration..."
+          sudo -u postgres psql -c "SHOW port;"
           sudo -u postgres psql postgres -c "ALTER USER postgres WITH PASSWORD '$POSTGRES_PASSWORD';"
+      
+      # - name: Check PostgreSQL Version
+      #   run: |
+      #     sudo -u postgres psql -c "SHOW server_version;"
+      #     ls /usr/lib/postgresql/
+      #     echo "Checking PostgreSQL port from configuration..."
+      #     sudo -u postgres psql -c "SHOW port;"
+
+      - name: Add TimescaleDB Package
+        run: |
+          echo "deb https://packagecloud.io/timescale/timescaledb/ubuntu/ $(lsb_release -c -s) main" | sudo tee /etc/apt/sources.list.d/timescaledb.list
+          wget --quiet -O - https://packagecloud.io/timescale/timescaledb/gpgkey | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/timescaledb.gpg
+          sudo apt-get update -y
+      
+      - name: Install and Configure TimescaleDB Extension
+        run: |
+          sudo apt-get install -y timescaledb-2-postgresql-17 postgresql-client-17
+          sudo timescaledb-tune --yes
+          sudo systemctl restart postgresql
+          sudo -u postgres psql -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"
+          
       - name: Create Python Virtual Environment and Install Dependencies
         run: |
           python -m venv AISdb
@@ -134,10 +174,12 @@ jobs:
           python -m pip install maturin
           maturin develop --release --extras=test,docs
           python -m pip install --upgrade pytest pytest-dotenv pytest-cov furl hypothesis trustme astor pyopenssl isort pydirectory
+      
       - name: Run Tests
         run: |
           source ./AISdb/bin/activate
           pytest ./aisdb/tests/ --ignore=./aisdb/tests/test_014_marinetraffic.py --maxfail=10
+      
       - name: Clean Up
         run: |
           rm -rf AISdb
@@ -198,14 +240,43 @@ jobs:
 
       - name: Install PostgreSQL
         run: |
-          brew install postgresql@14
-          brew services start postgresql@14
-          brew link postgresql@14 --force
+          brew update
+          brew install postgresql@17
+          brew link postgresql@17 --force
+          brew services start postgresql@17
           brew cleanup
+
+      - name: Check PostgreSQL version
+        run: |
+          brew list | grep postgresql
 
       - name: Configure PostgreSQL
         run: |
           psql postgres -c "CREATE ROLE postgres WITH LOGIN SUPERUSER PASSWORD '${{ env.POSTGRES_PASSWORD }}';"
+
+      - name: Install TimescaleDB
+        run: |
+          brew tap timescale/tap
+          brew install timescaledb
+          timescaledb-tune --quiet --yes
+          brew services restart postgresql@17
+          brew cleanup
+
+      - name: Setup TimescaleDB
+        run: |
+          TSDB_PATH=$(brew --prefix timescaledb)/bin
+          
+          if [ -f "$TSDB_PATH/timescaledb_move.sh" ]; then
+            cd "$TSDB_PATH"
+            ./timescaledb_move.sh
+          else
+            echo "Error: timescaledb_move.sh not found!"
+            exit 1
+          fi
+          
+          brew services restart postgresql@17
+          sleep 5
+          psql -U postgres -d postgres -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"
 
       - name: Create Python Virtual Environment and Install Dependencies
         run: |
