Update CIs

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -420,41 +420,41 @@ jobs:
           command: upload
           args: --non-interactive --skip-existing *
 
-  publish-docs:
-    runs-on: ubuntu-latest
-    needs: [release]
-    # needs: [linux]
-    strategy:
-      matrix:
-        target: [ x86_64 ]
-    steps:
-      - uses: actions/checkout@v4
+  # publish-docs:
+  #   runs-on: ubuntu-latest
+  #   needs: [release]
+  #   # needs: [linux]
+  #   strategy:
+  #     matrix:
+  #       target: [ x86_64 ]
+  #   steps:
+  #     - uses: actions/checkout@v4
       
-      - uses: actions/setup-python@v5
-        with:
-          python-version: '3.10'
+  #     - uses: actions/setup-python@v5
+  #       with:
+  #         python-version: '3.10'
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip || exit 1
-          python -m pip install aisdb || exit 1
-          python -m pip install sphinx sphinx-rtd-theme matplotlib joblib || exit 1
+  #     - name: Install dependencies
+  #       run: |
+  #         python -m pip install --upgrade pip || exit 1
+  #         python -m pip install aisdb || exit 1
+  #         python -m pip install sphinx sphinx-rtd-theme matplotlib joblib || exit 1
             
-      - name: Build docs
-        run: |
-          sphinx-apidoc --separate --force --implicit-namespaces --module-first -o docs/source/api aisdb aisdb/tests/*
-          python -m sphinx -a -j auto -b=html docs/source docs/dist_sphinx
+  #     - name: Build docs
+  #       run: |
+  #         sphinx-apidoc --separate --force --implicit-namespaces --module-first -o docs/source/api aisdb aisdb/tests/*
+  #         python -m sphinx -a -j auto -b=html docs/source docs/dist_sphinx
 
-      - name: Upload Pages artifact
-        uses: actions/upload-pages-artifact@v2
-        with:
-          path: docs/dist_sphinx
+  #     - name: Upload Pages artifact
+  #       uses: actions/upload-pages-artifact@v2
+  #       with:
+  #         path: docs/dist_sphinx
         
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v2
+  #     - name: Deploy to GitHub Pages
+  #       id: deployment
+  #       uses: actions/deploy-pages@v2
         
-      - name: Clean Up
-        run: |
-          rm -rf gh-pages
-          rm -rf docs/dist_sphinx
+  #     - name: Clean Up
+  #       run: |
+  #         rm -rf gh-pages
+  #         rm -rf docs/dist_sphinx
